### ISSUE TITLE
Deprecated Bower

### ISSUE THREAD

**Issue by gabriel-tessier** [jctt1983/HeadsUp#6]
npm install -g bower
 
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

According to the readme the point 4 of installation 

run $ bower install

Return   ENOENT No bower.json present

Maybe bower was already removed?? if so need to update the readme.

Also if you can add the command lines to create the venv

pip install virtualenv
virtualenv -p /usr/bin/python2.7 venv_headsup
source venv_headsup/bin/activate

And update the Prerequisites section

    Python 2.7.X & pip

**Comment by gabriel-tessier** [comment]
@jctt1983 
Can you check after bower and update the readme according to the need..

**Comment by jctt1983** [comment]
Indeed bower was removed from this project so I started using webpack to replace the tasks that bower used to do. But I've also made shortcuts in package.json to abstract the webpack tasks.

So as of now, you can use 
```
$ npm run build:dev
$ npm run build:prd
$ npm run dev:watch # watch changes in js files & apply JS transpilers
```

I'm going to update the readme now :)

**Comment by gabriel-tessier** [comment]
All done!
Thanks.
